## Basic Configuration

baseurl = "http://thaissa.me/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Thaíssa Falbo"
title = "Thaíssa Falbo"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Thaíssa Falbo"
intro = "Full-Stack Developer"
description = "[@Udacity](http://www.udacity.com)"
authorimage = "avatar.jpeg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
# [params.meta]
# description = "Simple minimalist theme"
# keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "tfalbo"
instagram = "tatazete"
linkedin = "thaissa"
twitter = "t_falbolous"
facebook = "thaissa"
email = "me@thaissa.me"

## Extras
[params.extra]
copyright = "© 2018. Thaissa Falbo. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = false

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "https://medium.com/falbolous-blog"
